import {
  FaWix,
  FaShopify,
  FaMailchimp,
  FaPaypal,
  FaIntercom,
  FaGoogle,
  FaEvernote,
  FaMicrosoft,
  FaInvision,
} from "react-icons/fa";

const tableData = [
  {
    brand: FaWix,
    name: "Wix",
    description: "Develop a personalized fit...",
    members: [
      "https://randomuser.me/api/portraits/men/1.jpg",
      "https://randomuser.me/api/portraits/women/1.jpg",
    ],
    categories: "Automation",
    tags: "#DigitalTransformation",
    nextMeeting: "in 30 minutes",
    color: "#ff5722", // Wix color
    messages: 2,
  },
  {
    brand: FaShopify,
    name: "Shopify",
    description: "Introduce a cloud-based p...",
    members: [
      "https://randomuser.me/api/portraits/men/2.jpg",
      "https://randomuser.me/api/portraits/women/2.jpg",
      "https://randomuser.me/api/portraits/men/3.jpg",
    ],
    categories: "E-commerce, B2B",
    tags: "#OnlineShopping",
    nextMeeting: "Tomorrow",
    color: "#96bf48", // Shopify color
    messages: 0,
  },
  {
    brand: FaMailchimp,
    name: "MailChimp",
    description: "Develop a mobile app aim...",
    members: [
      "https://randomuser.me/api/portraits/men/4.jpg",
      "https://randomuser.me/api/portraits/women/3.jpg",
      "https://randomuser.me/api/portraits/men/5.jpg",
      "https://randomuser.me/api/portraits/women/4.jpg",
    ],
    categories: "SAAS, Mobile",
    tags: "#TechInnovation",
    nextMeeting: "Tomorrow",
    color: "#ffe01b", // MailChimp color
    messages: 0,
  },
  {
    brand: FaPaypal,
    name: "PayPal",
    description: "This program could inclu...",
    members: [
      "https://randomuser.me/api/portraits/men/6.jpg",
      "https://randomuser.me/api/portraits/women/5.jpg",
      "https://randomuser.me/api/portraits/men/7.jpg",
      "https://randomuser.me/api/portraits/women/6.jpg",
      "https://randomuser.me/api/portraits/men/8.jpg",
    ],
    categories: "Marketplace",
    tags: "#BuySellOnline",
    nextMeeting: "in 6 hours",
    color: "#003087", // PayPal color
    messages: 7,
  },
  {
    brand: FaIntercom,
    name: "Intercom",
    description: "Implement an AI-driven C...",
    members: [
      "https://randomuser.me/api/portraits/men/9.jpg",
      "https://randomuser.me/api/portraits/women/7.jpg",
      "https://randomuser.me/api/portraits/men/10.jpg",
      "https://randomuser.me/api/portraits/women/8.jpg",
      "https://randomuser.me/api/portraits/men/11.jpg",
      "https://randomuser.me/api/portraits/women/9.jpg",
      "https://randomuser.me/api/portraits/men/12.jpg",
    ],
    categories: "Technology, SAAS",
    tags: "#SmartFinance",
    nextMeeting: "in 1 hour",
    color: "#1f8eed", // Intercom color
    messages: 9,
  },
  {
    brand: FaGoogle,
    name: "Google",
    description: "Offer a comprehensive cy...",
    members: [
      "https://randomuser.me/api/portraits/men/13.jpg",
      "https://randomuser.me/api/portraits/women/10.jpg",
      "https://randomuser.me/api/portraits/men/14.jpg",
      "https://randomuser.me/api/portraits/women/11.jpg",
      "https://randomuser.me/api/portraits/men/15.jpg",
      "https://randomuser.me/api/portraits/women/12.jpg",
      "https://randomuser.me/api/portraits/men/16.jpg",
      "https://randomuser.me/api/portraits/women/13.jpg",
    ],
    categories: "Finance, Automation",
    tags: "#SmartFinance",
    nextMeeting: "in 30 minutes",
    color: "#4285f4", // Google color
    messages: 5,
  },
  {
    brand: FaEvernote,
    name: "Evernote",
    description: "This could include smart...",
    members: [
      "https://randomuser.me/api/portraits/men/17.jpg",
      "https://randomuser.me/api/portraits/women/14.jpg",
      "https://randomuser.me/api/portraits/men/18.jpg",
      "https://randomuser.me/api/portraits/women/15.jpg",
      "https://randomuser.me/api/portraits/men/19.jpg",
      "https://randomuser.me/api/portraits/women/16.jpg",
      "https://randomuser.me/api/portraits/men/20.jpg",
      "https://randomuser.me/api/portraits/women/17.jpg",
      "https://randomuser.me/api/portraits/men/21.jpg",
    ],
    categories: "Transportation",
    tags: "#LogisticsTech",
    nextMeeting: "Next month",
    color: "#2dbe60", // Evernote color
    messages: 0,
  },
  {
    brand: FaMicrosoft,
    name: "Microsoft",
    description: "Launch an advisory serv...",
    members: [
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/women/18.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/women/19.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/women/20.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
      "https://randomuser.me/api/portraits/women/21.jpg",
      "https://randomuser.me/api/portraits/men/26.jpg",
      "https://randomuser.me/api/portraits/women/22.jpg",
    ],
    categories: "Publishing, B2C",
    tags: "#B2CMarketing",
    nextMeeting: "No contact",
    color: "#f25022", // Microsoft color
    messages: 14,
  },
  {
    brand: FaInvision,
    name: "Invision",
    description: "The tool would analyze t...",
    members: [
      "https://randomuser.me/api/portraits/men/27.jpg",
      "https://randomuser.me/api/portraits/women/23.jpg",
      "https://randomuser.me/api/portraits/men/28.jpg",
      "https://randomuser.me/api/portraits/women/24.jpg",
      "https://randomuser.me/api/portraits/men/29.jpg",
      "https://randomuser.me/api/portraits/women/25.jpg",
      "https://randomuser.me/api/portraits/men/30.jpg",
      "https://randomuser.me/api/portraits/women/26.jpg",
      "https://randomuser.me/api/portraits/men/31.jpg",
      "https://randomuser.me/api/portraits/women/27.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
    ],
    categories: "Web Services",
    tags: "#APIIntegration",
    nextMeeting: "Next month",
    color: "#ff3366", // Invision color
    messages: 0,
  },
];

export default tableData;
